# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/


stages:
  - build
  - test
  - deploy

#image: gcc
image: gcc

generator:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  tags:
    - docker_miem
  before_script:
 #    - rmdir -rf Generator/source/build
     - apt update && apt -y install make && apt -y install cmake
     - mkdir Generator/source/build
  script:
    - cd Generator/source/build
    - pwd
    - cmake ../
    - make
  artifacts:
    paths:
      - Generator/source/build/prog
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  tags:
    - docker_miem
  script:
    - pwd
    - ls
    - ls ./Generator
    - ls ./Generator/source
    - ls ./Generator/source/build
    - ls ./Generator/source/build/tests
    - ./Generator/source/build/tests/tests

